---
permalink: deploy/concept-migration-of-disaster-recovery-setup-from-windows-to-appliance.html 
sidebar: sidebar 
keywords: migration, windows, SRM, appliance, 
summary: 'Si vous utilisez Windows site Recovery Manager (SRM) pour la reprise après incident et que vous souhaitez utiliser l"appliance SRM pour la même configuration, vous devez migrer la configuration de la reprise après incident Windows vers la solution SRM basée sur l"appliance.' 
---
= Migration de Windows SRM vers l'appliance SRM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez Windows site Recovery Manager (SRM) pour la reprise après incident et que vous souhaitez utiliser l'appliance SRM pour la même configuration, vous devez migrer la configuration de la reprise après incident Windows vers la solution SRM basée sur l'appliance.

Les étapes de la migration de la reprise sur incident sont les suivantes :

. Mise à niveau de votre appliance virtuelle existante pour VSC, VASA Provider et SRA vers la version 9.7.1.
+
link:task-upgrade-to-the-9-7-1-virtual-appliance-for-vsc-vasa-provider-and-sra.html["Effectuez la mise à niveau vers l'appliance virtuelle 9.7.1 pour VSC, VASA Provider et SRA"^]

. Migration de l'adaptateur de réplication du stockage Windows vers SRA basé sur l'appliance.
. Migration des données Windows SRM vers l'appliance SRM.


https://docs.vmware.com/en/Site-Recovery-Manager/8.2/com.vmware.srm.install_config.doc/GUID-F39A84D3-2E3D-4018-97DD-5D7F7E041B43.html["Cliquez ici"^] pour des étapes détaillées.
