---
permalink: deploy/reference-error-during-fresh-deployment-of-virtual-appliance-for-vsc-vasa-provider-and-sra.html 
sidebar: sidebar 
keywords: error, during, fresh, deployment, virtual, appliance, vsc, vasa, provider, sra, 
summary: 'Erreur lors du nouveau déploiement de l"appliance virtuelle pour VSC, VASA Provider et SRA' 
---
= Erreur lors du nouveau déploiement de l'appliance virtuelle pour VSC, VASA Provider et SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Problème

Le journal d'erreurs « VMware Tools OVF vCenter configuration introuvable » s'affiche lors du nouveau déploiement de l'appliance virtuelle pour VSC, VASA Provider et SRA lorsque l'adresse vCenter ServerIPv4 n'est pas valide.



== Cause

Virtual Appliance pour VSC, VASA Provider et SRA prend en charge les adresses IPv4 et IPv6. Si l'utilisateur fournit une adresse IPv4 pour vCenter Server qui n'est pas disponible sur le réseau et qu'aucune adresse IPv6 n'est fournie, ces messages d'enregistreur s'affichent sur la console de maintenance.



== Action corrective

Pour supprimer l'erreur, procédez comme suit :

. Connectez-vous à la console de maintenance.
. Accéder à la coque de diagnostic.
. Remplacez l'utilisateur de "diag" par "root" à l'aide de ``sudo su``commande.
. Modifiez le fichier d'interface à l'aide de l'éditeur vi `vi /etc/network/interface`.
. Supprimer l'entrée pour « inet6 ».
. Enregistrez le fichier et redémarrez l'appliance virtuelle pour VSC, VASA Provider et SRA.


Après le redémarrage de l'appliance virtuelle, aucun message d'erreur n'est observé.
