---
permalink: deploy/reference-sra-fails-to-perform-optimally-in-a-highly-scaled-environment.html 
sidebar: sidebar 
keywords: sra, fails, to, perform, optimally, highly, scaled, environment, 
summary: 'SRA n"assure pas des performances optimales dans un environnement hautement évolutif' 
---
= SRA n'assure pas des performances optimales dans un environnement hautement évolutif
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Problème

SRA n'assure pas le bon fonctionnement des environnements à grande échelle (si vous exécutez des limites maximales spécifiées par VMware, comme 250 RPV, 250 RPS ou 5000 machines virtuelles), et vous risquez de remarquer des problèmes, tels qu'une erreur de délai d'attente ou un délai d'expiration ONTAP.



== Action corrective

Vous devez modifier les intervalles de temporisation.

link:reference-configure-storage-replication-adapter-for-highly-scaled-environment.html["Configuration de l'adaptateur de réplication du stockage pour l'environnement à grande échelle"]

[NOTE]
====
Vous pouvez également modifier les paramètres de mémoire pour l'évolutivité et les performances de votre appliance virtuelle pour VSC, VASA Provider et SRA dans des configurations extrêmement évolutives.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/tune_memory_settings_of_VM_VSC%2C_VASA_Provider%2C_and_SRA_for_scale_and_performance[]

====