---
permalink: deploy/task-enable-datastore-mounting-across-different-subnets.html 
sidebar: sidebar 
keywords: enabling, datastore, mounting, across, different, subnets, 
summary: 'Si vous utilisez iSCSI ou NFS et que le sous-réseau est différent entre vos hôtes ESXi et votre système de stockage, vous devez modifier les fichiers de préférences de Virtual Storage Console pour VMware vSphere. Si vous ne modifiez pas le fichier de préférences, l"approvisionnement du datastore échoue car (VSC) ne peut pas monter le datastore.' 
---
= Activez le montage du datastore sur différents sous-réseaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez iSCSI ou NFS et que le sous-réseau est différent entre vos hôtes ESXi et votre système de stockage, vous devez modifier les fichiers de préférences de Virtual Storage Console pour VMware vSphere. Si vous ne modifiez pas le fichier de préférences, l'approvisionnement du datastore échoue car (VSC) ne peut pas monter le datastore.

.Description de la tâche
Lorsque le provisionnement du datastore échoue, VSC consigne les messages d'erreur suivants :

`Unable to continue. No ip addresses found when cross-referencing kernel ip addresses and addresses on the controller.`

`Unable to find a matching network to NFS mount volume to these hosts.` ``

.Étapes
. Connectez-vous à votre instance de vCenter Server.
. Lancez la console de maintenance à l'aide de votre machine virtuelle d'appliance unifiée.
+
link:task-access-virtual-appliance-maiintenance-console-options.html["Accédez aux options de la console de maintenance de l'appliance virtuelle pour VSC, VASA Provider et SRA"]

. Entrez `4` Pour accéder à l'option *support et Diagnostics*.
. Entrez `2` Pour accéder à l'option *Access diagnostic Shell*.
. Entrez `vi /opt/netapp/vscserver/etc/kamino/kaminoprefs.xml` pour mettre à jour le `kaminoprefs.xml` fichier.
. Mettez à jour le `kaminoprefs.xml` fichier.
+
[cols="1a,1a"]
|===
| Si vous utilisez... | Procédez comme ça... 


 a| 
ISCSI
 a| 
Modifiez la valeur de la clé d'entrée `default.allow.iscsi.mount.networks` De TOUT à la valeur de vos réseaux hôtes VMware ESXi.



 a| 
NFS
 a| 
Modifiez la valeur de la clé d'entrée `default.allow.nfs.mount.networks` De TOUT à la valeur de vos réseaux hôtes VMware ESXi.

|===
+
Le fichier de préférences contient des exemples de valeurs pour ces clés de saisie.

+
[NOTE]
====
La valeur « TOUS » ne signifie pas tous les réseaux. La valeur « TOUS » permet d'utiliser tous les réseaux de correspondance, entre l'hôte et le système de stockage, pour le montage de datastores. Lorsque vous spécifiez des réseaux hôtes, vous ne pouvez activer le montage que sur les sous-réseaux spécifiés.

====
. Enregistrez et fermez le `kaminoprefs.xml` fichier.

