---
permalink: deploy/task-configure-sra-on-srm-appliance.html 
sidebar: sidebar 
keywords: configuring, sra, srm, appliance, 
summary: 'Une fois l"appliance SRM déployée, vous devez configurer SRA sur l"appliance SRM. La configuration de SRA permet de communiquer avec SRM Appliance et SRA pour la gestion de la reprise après incident. Vous devez stocker l"appliance virtuelle pour les informations d"identification VSC, VASA Provider et SRA (adresse IP et mot de passe d"administrateur) dans l"appliance SRM pour permettre la communication entre SRM Appliance et SRA.' 
---
= Configurez SRA sur l'appliance SRM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois l'appliance SRM déployée, vous devez configurer SRA sur l'appliance SRM. La configuration de SRA permet de communiquer avec SRM Appliance et SRA pour la gestion de la reprise après incident. Vous devez stocker l'appliance virtuelle pour les informations d'identification VSC, VASA Provider et SRA (adresse IP et mot de passe d'administrateur) dans l'appliance SRM pour permettre la communication entre SRM Appliance et SRA.

.Avant de commencer
Vous devez télécharger le `tar.gz` Fichier vers l'appliance SRM.

.Description de la tâche
La configuration de SRA sur SRM Appliance stocke les informations d'identification SRA dans l'appliance SRM.

.Étapes
. Connectez-vous à l'aide du compte administrateur à l'appliance SRM à l'aide de putty.
. Basculer vers l'utilisateur root à l'aide de la commande : `su root`
. Dans le journal location, entrez la commande pour obtenir l'ID docker utilisé par SRA `docker ps -l`
. Pour vous connecter à l'ID de conteneur, entrez la commande `docker exec -it -u srm <container id> sh`
. Configurez SRM avec l'appliance virtuelle pour VSC, VASA Provider, ainsi que l'adresse IP et le mot de passe de SRA à l'aide de la commande : `perl command.pl -I <va-IP> administrator <va-password>`
+
Un message de confirmation de la mémorisation des identifiants de stockage s'affiche. SRA peut communiquer avec le serveur SRA à l'aide de l'adresse IP, du port et des informations d'identification fournis.


