---
permalink: deploy/task-set-default-credentials-for-storage-systems.html 
sidebar: sidebar 
keywords: setting, default, credentials, storage, systems, 
summary: 'Vous pouvez utiliser Virtual Storage Console pour VMware vSphere pour définir les informations d"identification par défaut d"un système de stockage sur votre serveur vCenter.' 
---
= Définissez les identifiants par défaut des systèmes de stockage
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser Virtual Storage Console pour VMware vSphere pour définir les informations d'identification par défaut d'un système de stockage sur votre serveur vCenter.

.Avant de commencer
Vous devez avoir sélectionné le serveur vCenter que vous souhaitez utiliser pour créer des informations d'identification par défaut.

.Description de la tâche
Si vous configurez des identifiants par défaut pour les systèmes de stockage, (VSC) utilise ces identifiants pour vous connecter à un système de stockage que VSC vient de découvrir. Si les informations d'identification par défaut ne fonctionnent pas, vous devez vous connecter manuellement au système de stockage. Prise en charge de VSC et SRA via l'ajout des identifiants du système de stockage au niveau du cluster ou du niveau. Cependant, VASA Provider ne fonctionne qu'avec les identifiants au niveau du cluster.

.Étapes
. Sur la page VSC *Home*, cliquez sur menu:Paramètres[Paramètres d'administration > configurer les informations d'identification par défaut pour le système de stockage].
. Dans la boîte de dialogue *informations d'identification par défaut du système de stockage*, entrez le nom d'utilisateur et le mot de passe du système de stockage.
+
En fonction du nom d'utilisateur et du mot de passe, les informations d'identification du contrôleur de stockage sont attribuées dans ONTAP. Les identifiants du contrôleur de stockage peuvent être soit le compte d'administrateur, soit un compte personnalisé utilisant le contrôle d'accès basé sur des rôles (RBAC).

+
Vous ne pouvez pas utiliser VSC pour modifier les rôles associés à la paire nom d'utilisateur et mot de passe du contrôleur de stockage. Pour modifier ou créer un nouveau rôle utilisateur ONTAP à utiliser avec l'appliance virtuelle pour VSC, VASA Provider et SRA, vous pouvez utiliser System Manager.

+
Consultez la section « Configuration des rôles et privilèges utilisateur » dans le document _Virtual Storage Console, VASA Provider et Storage Replication adapter pour VMware® vSphere Deployment and Setup Guide pour la version 9.7_.

. Cliquez sur *OK* pour enregistrer les informations d'identification par défaut.


.Une fois que vous avez terminé
Si vous avez mis à jour les informations d'identification du système de stockage parce qu'un système de stockage a signalé l'état « échec d'authentification », vous devez cliquer sur l'option *REDÉCOUVRIR TOUT* disponible sur la page systèmes de stockage. Dans ce cas, VSC tente de se connecter au système de stockage à l'aide des nouvelles informations d'identification.
