---
permalink: manage/task-configure-protection-groups.html 
sidebar: sidebar 
keywords: configuring, protection, groups, 
summary: Vous devez créer des groupes de protection pour protéger un groupe de machines virtuelles sur le site protégé. 
---
= Configuration des groupes de protection
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer des groupes de protection pour protéger un groupe de machines virtuelles sur le site protégé.

.Avant de commencer
Vous devez vous assurer que les sites source et cible sont configurés pour les sites suivants :

* Même version de SRM installée
* Le datastore vvols est configuré avec une réplication activée et un datastore monté
* Profils de capacité de stockage similaires
* Règles de stockage des serveurs virtuels similaires avec fonctionnalité de réplication qui doit être mappée dans SRM
* Ordinateurs virtuels
* Sites protégés et de reprise par paires
* Les datastores source et de destination doivent être montés sur les sites respectifs


.Étapes
. Connectez-vous à vCenter Server, puis cliquez sur menu:site Recovery[protection Groups].
. Dans le volet *protection Groups*, cliquez sur *Nouveau*.
. Spécifiez un nom et une description pour le groupe de protection, la direction, puis cliquez sur *SUIVANT*.
. Dans le champ *Type*, sélectionnez l'une des options suivantes :
+
[cols="1a,1a"]
|===
| Pour... | Option de champ de type... 


 a| 
*Datastore traditionnel*
 a| 
Groupes de datastores (réplication basée sur les baies)



 a| 
*VVvols datastore*
 a| 
Volumes virtuels (réplication vvol)

|===
+
Le domaine de panne n'est rien d'autre que les SVM avec la réplication activée. Les SVM qui ont uniquement peering mis en œuvre et sans problèmes sont affichés.

. Dans l'onglet *Replication Groups*, sélectionnez la paire de matrices activée ou les groupes de réplication possédant la machine virtuelle que vous avez configurée, puis cliquez sur *NEXT*.
+
Toutes les machines virtuelles du groupe de réplication sont ajoutées au groupe de protection.

. Sélectionnez le plan de reprise existant ou créez un nouveau plan en cliquant sur *Ajouter au nouveau plan de reprise*.
. Dans l'onglet *prêt à compléter*, vérifiez les détails du groupe de protection que vous avez créé, puis cliquez sur *Terminer*.

