---
permalink: manage/task-mount-datastores-on-host.html 
sidebar: sidebar 
keywords: mounting, datastore, on, additional, hosts, 
summary: 'Le montage d"un datastore permet d"accéder au stockage à des hôtes supplémentaires. Après avoir ajouté les hôtes à votre environnement VMware, vous pouvez monter le datastore sur les hôtes supplémentaires.' 
---
= Montage du datastore sur des hôtes supplémentaires
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le montage d'un datastore permet d'accéder au stockage à des hôtes supplémentaires. Après avoir ajouté les hôtes à votre environnement VMware, vous pouvez monter le datastore sur les hôtes supplémentaires.

Vous devez vous assurer que les détails de sous-réseau de tous les réseaux auxquels le ESXi hébergé est connecté sont saisis dans le `Kaminoprefs.xml`.

Reportez-vous à la section activation du montage de datastores sur différents sous-réseaux du _VSC 9.6 Deployment and Setup Guide_.

.Étapes
. Dans la page client vSphere *Home*, cliquez sur *hôtes et clusters*.
. Dans le volet de navigation, sélectionnez le centre de données qui contient l'hôte.
. Répétez l'étape 2 pour tout hôte supplémentaire.
. Cliquez avec le bouton droit sur l'hôte et sélectionnez menu :NetApp VSC [Mount datastores].
. Sélectionnez les datastores à monter, puis cliquez sur *OK*.

