---
permalink: manage/task-provision-datastores.html 
sidebar: sidebar 
keywords: provisioning, datastores, 
summary: 'Le provisionnement d"un datastore crée un conteneur logique pour vos machines virtuelles et leurs disques de machines virtuelles (VMDK). Vous pouvez provisionner un datastore, puis le relier à un hôte unique, à tous les hôtes d"un cluster ou à tous les hôtes d"un data Center.' 
---
= Provisionner les datastores
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le provisionnement d'un datastore crée un conteneur logique pour vos machines virtuelles et leurs disques de machines virtuelles (VMDK). Vous pouvez provisionner un datastore, puis le relier à un hôte unique, à tous les hôtes d'un cluster ou à tous les hôtes d'un data Center.

.Avant de commencer
* Pour provisionner un datastore sur un SVM connecté directement à Virtual Storage Console (VSC), vous devez avoir ajouté le SVM à VSC en utilisant un compte utilisateur disposant des privilèges appropriés, et non le compte utilisateur vsadmin par défaut ou le rôle vsadmin.
+
Vous pouvez également provisionner un datastore en ajoutant un cluster.

* Vous devez vous assurer que les détails de sous-réseau de tous les réseaux auxquels le ESXi hébergé est connecté sont saisis dans le `kaminoprefs.xml`.
+
Pour plus d'informations, reportez-vous à la section « activation du montage de datastores sur différents sous-réseaux » du _VSC 9.6 Deployment and Setup Guide_.

* Si vous utilisez NFS ou iSCSI et que le sous-réseau est différent entre vos hôtes ESXi et votre système de stockage, les paramètres NFS ou iSCSI dans `kaminoprefs` Le fichier de préférences doit inclure des masques de sous-réseau de l'hôte ESXi.
+
Ce fichier de préférences s'applique également à la création du datastore VVol. _Virtual Storage Console, VASA Provider et Storage Replication adapter Guide de déploiement et de configuration pour la version 9.6_ contient plus d'informations sur le fichier de préférences et sur l'activation du montage de datastores sur différents sous-réseaux.

* Si vous avez activé VASA Provider et que vous souhaitez spécifier des profils de capacité de stockage pour vos datastores NFS ou VMFS, vous devez avoir créé un ou plusieurs profils de fonctionnalité de stockage.
* Pour créer un datastore NFSv4.1, vous devez avoir activé NFSv4.1 au niveau du SVM.


.Description de la tâche
L'option *Provision datastore* vous permet de spécifier un profil de capacité de stockage pour le datastore. Les profils de capacité de stockage facilitent la spécification d'objectifs de niveau de service (SLO) cohérents et simplifient le processus de provisionnement. Vous ne pouvez spécifier un profil de capacité de stockage que si vous avez activé VASA Provider. L'appliance virtuelle pour VSC, VASA Provider et SRA prend en charge les protocoles suivants :

* NFS v3 et NFS v4.1
* VMFS5 et VMFS6


VSC peut créer un datastore sur un volume NFS ou un LUN :

* Pour un datastore NFS, VSC crée un volume NFS sur le système de stockage, puis met à jour les règles d'exportation.
* Pour un datastore VMFS, VSC crée un nouveau volume (ou utilise un volume existant, si vous avez sélectionné cette option), puis crée un LUN et un groupe initiateur.


[NOTE]
====
VMware ne prend pas en charge NFSv4.1 avec les clusters de datastores.

====
Si aucun profil de capacité de stockage n'est spécifié lors du provisionnement, vous pouvez utiliser la page mappage du stockage pour mapper un datastore vers un profil de capacité de stockage.

.Étapes
. Vous pouvez accéder à l'assistant de provisionnement de datastores à l'aide de l'une des méthodes suivantes :
+
[cols="1a,1a"]
|===
| Si vous sélectionnez ... | Effectuez les opérations suivantes... 


 a| 
*Page d'accueil du client vSphere*
 a| 
.. Cliquez sur *hôtes et clusters*.
.. Dans le volet de navigation, sélectionnez le datacenter sur lequel vous souhaitez provisionner le datastore.
.. Pour spécifier les hôtes à monter le datastore, reportez-vous à l'étape suivante.




 a| 
*Page d'accueil de Virtual Storage Console*
 a| 
.. Cliquez sur *Aperçu*.
.. Cliquez sur l'onglet *pour commencer*.
.. Cliquez sur le bouton *Provision*.
.. Cliquez sur *Parcourir* pour sélectionner la destination de provisionnement du datastore selon l'étape suivante.


|===
. Spécifiez les hôtes sur lesquels vous souhaitez monter le datastore.
+
[cols="1a,1a"]
|===
| Pour rendre le datastore disponible à... | Procédez comme ça... 


 a| 
Tous les hôtes d'un data Center
 a| 
Cliquez avec le bouton droit sur un data Center, puis sélectionnez menu :NetApp VSC [Provision datastore].



 a| 
Tous les hôtes d'un cluster
 a| 
Cliquez avec le bouton droit sur un cluster hôte, puis sélectionnez menu :NetApp VSC [Provision datastore].



 a| 
Un hôte unique
 a| 
Cliquez avec le bouton droit sur un hôte et sélectionnez menu :NetApp VSC [Provision datastore].

|===
. Renseignez les champs de la boîte de dialogue *Nouveau datastore* pour créer le datastore.
+
La plupart des champs de la boîte de dialogue sont explicites. Le tableau suivant décrit certains des champs pour lesquels vous pouvez avoir besoin de conseils.

+
[cols="1a,1a"]
|===
| Section | Description 


 a| 
Généralités
 a| 
La section *général* de la boîte de dialogue *New datastore provisioning* fournit des options permettant de saisir la destination, le nom, la taille, le type et le protocole du nouveau datastore. Vous pouvez sélectionner le protocole *NFS* ou *VMFS* pour configurer un datastore traditionnel. Le type de datastore VVOL est utilisé pour configurer un datastore VVOL. Si VASA Provider est activé, vous pouvez également décider d'utiliser des profils de fonctionnalité de stockage. L'option *datastore cluster* est disponible uniquement pour les datastores traditionnels. Vous devez utiliser l'option *Advanced* pour spécifier le système de fichiers *VMFS5* ou *VMFS6*.



 a| 
Adieu les migrations de données onéreuses
 a| 
Vous pouvez sélectionner l'un des profils de capacité de stockage répertoriés si vous avez sélectionné l'option dans la section *général*. Les valeurs recommandées par le système pour le système de stockage et la machine virtuelle de stockage sont remplies pour faciliter la mise en place. Mais vous pouvez modifier les valeurs si nécessaire.



 a| 
Les attributs de stockage
 a| 
Par défaut, VSC renseigne les valeurs recommandées pour les options *Aggregates* et *volumes*. Vous pouvez personnaliser les valeurs en fonction de vos besoins. L'option *réserve d'espace* disponible dans le menu *Avancé* est également renseignée pour donner des résultats optimaux.



 a| 
Récapitulatif
 a| 
Vous pouvez consulter le récapitulatif des paramètres que vous avez spécifiés pour le nouveau datastore.

|===
. Dans la section *Résumé*, cliquez sur *Terminer*.

