---
permalink: manage/task-edit-esxi-host-settings.html 
sidebar: sidebar 
keywords: editing, esxi, host, settings, for, vsc, vasa, provider, and, sra, 
summary: 'Le tableau de bord de l"appliance virtuelle pour Virtual Storage Console (VSC), VASA Provider et Storage Replication adapter (SRA) vous permet de modifier les paramètres de votre hôte ESXi.' 
---
= Modifiez les paramètres d'hôte ESXi pour VSC, VASA Provider et SRA
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le tableau de bord de l'appliance virtuelle pour Virtual Storage Console (VSC), VASA Provider et Storage Replication adapter (SRA) vous permet de modifier les paramètres de votre hôte ESXi.

Vous devez avoir configuré un système hôte ESXi pour votre instance vCenter Server.

En cas de problème avec les paramètres de votre hôte VMware ESXi, le problème s'affiche dans le portlet systèmes hôtes VMware ESXi du tableau de bord. Vous pouvez cliquer sur le problème pour afficher le nom d'hôte ou l'adresse IP de l'hôte ESXi qui présente le problème.

.Étapes
. Dans la page client vSphere *Home*, cliquez sur *Virtual Storage Console*.
. Modifiez les paramètres de l'hôte VMware ESXi.
+
[cols="1a,1a"]
|===
| Si vous souhaitez modifier les paramètres de l'hôte VMware ESXi à partir de... | Procédez comme ça... 


 a| 
Problèmes affichés
 a| 
.. Cliquez sur le problème dans le portlet systèmes hôtes VMware ESXi.
.. Cliquez sur les noms d'hôte VMware ESXi pour lesquels vous souhaitez modifier les paramètres.
.. Cliquez avec le bouton droit de la souris sur le nom d'hôte ESXi, puis cliquez sur menu :NetApp VSC[Set Recommended Values].
.. Modifiez les paramètres requis, puis cliquez sur *OK*.




 a| 
Page d'accueil de vSphere client
 a| 
.. Cliquez sur menu:Menu[hôtes et clusters].
.. Cliquez avec le bouton droit sur l'hôte ESXi requis et sélectionnez menu :NetApp VSC[Set Recommended Value].
.. Cliquez sur *OK*.




 a| 
Portlet systèmes hôtes VMware ESXi
 a| 
.. Cliquez sur l'onglet *Ttional Dashboard* (Tableau de bord traditionnel) dans la section Overview (Présentation) de VSC.
.. Cliquez sur *Modifier les paramètres de l'hôte VMware ESXi*.
.. Sélectionnez le nom d'hôte ESXi dans l'onglet Paramètres de l'hôte et état pour lequel vous souhaitez modifier les paramètres, puis cliquez sur *SUIVANT*.
.. Sélectionnez les paramètres requis dans l'onglet Paramètres d'hôte recommandés, puis cliquez sur *Suivant*.
.. Vérifiez votre sélection dans l'onglet Résumé, puis cliquez sur *TERMINER*.


|===

